### ISSUE TITLE
Integrate automated tests with CI running at every build

### ISSUE THREAD

**Issue by gidili** [MetaCell/geppetto-scidash#388] opened 2019-09-04 13:57 UTC

**Comment by rgerkin** [comment] 2019-12-06 19:44
Duplicate of #398?

**Comment by ddelpiano** [comment] 2019-12-09 12:26
@rgerkin possible, this task will cover mainly the gluing between github and continous deployment so that automatically travis (or alternative) will trigger a new build of the code with the new changes and then will trigger the automated testing on top of the new code pushed in the branch. If we want to rely on travis (or alternative) builds history to keep track of these issues we can but #398 seems more something that can be achieved with google analytics. Adding this to the agenda to discuss it.

**Comment by gidili** [comment] 2019-12-09 12:36
@rgerkin Yeah I don't think it's a duplicate - this one is, like @ddelpiano says, about making it possible for tests to run as part of the build, so not even implementing the actual tests, just the infrastructure work to "integrate", while #398 it's about logging user activity and errors as they occur.

**Closed as completed** 2020-02-05 14:43 UTC
Labels: testing, deployment, estimate: 3
